apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-swarm-role
  namespace: swarm
rules:
  - apiGroups:
      - apps
    resources:
      - pods
      - statefulsets
    verbs:
      - get
      - watch
      - list
  - apiGroups: [""]
    resources:
      - pods
      - statefulsets
    verbs:
      - get
      - watch
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-swarm-rbac
  namespace: swarm
subjects:
  - kind: ServiceAccount
    name: default
    namespace: swarm
roleRef:
  kind: ClusterRole
  name: k8s-swarm-role
  apiGroup: rbac.authorization.k8s.io

